FROM node:18-alpine

# Install Docker CLI to exec into terminal container
RUN apk add --no-cache docker-cli

WORKDIR /app

COPY package.json .
RUN npm install

COPY . .

EXPOSE 1337

CMD ["node", "server.js"]