FROM alpine:latest

RUN apk add --no-cache \
    nmap \
    nmap-scripts \
    ttyd \
    bash \
    curl \
    bind-tools \
    nano \
    vim \
    iputils \
    net-tools \
    && rm -rf /var/cache/apk/*

EXPOSE 7681

CMD ["ttyd", "-p", "7681", "-c", "admin:admin", "bash"]